import { Metadata } from "next";
import dynamic from "next/dynamic";
import React from "react";

export const metadata: Metadata = {
  title: "Sign In",
  description: "Generated by create next app",
};

const SignInScreen = dynamic(() => import("@/components/sign-in"));

const SignIn = () => {
  return <SignInScreen />;
};

export default SignIn;
