import { Metadata } from "next";
import dynamic from "next/dynamic";
import React from "react";

export const metadata: Metadata = {
  title: "Conversation",
  description: "Generated by create next app",
};

const NoInternet = dynamic(() => import("@/components/no-internet"));

const NoInternetPage = () => {
  return <NoInternet />;
};

export default NoInternetPage;
